### ISSUE TITLE
Project assumes user has `commander` gem installed

### ISSUE THREAD

**Issue by immer** [xogroup/xo_dockerize#14]
When I ran the wizard, it didn't work.

```
 ./dockerize.rb this
/Users/rmassey/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- commander (LoadError)
        from /Users/rmassey/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./dockerize.rb:4:in `<main>'
```

I installed the gem

```
gem install commander
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: commander-4.4.0.gem (100%)
Successfully installed commander-4.4.0
2 gems installed
```

Now it works

```
 ./dockerize.rb this  
Web or Worker?
1. web
2. worker
?  
```

**Comment by nrodriguez** [comment]
Yea this is really due to me having such a hard time setting up a setup script to do all the cli commands strictly through bash. I'd love for a better way to set up a cli through bash so we don't have to rely on commander. If not, I was debating about bundling commander maybe through homebrew.

**Comment by nrodriguez** [comment]
I guess another option is to just have the overall install script do the commander install as well?
